const lessons=[
 {title:'Authority & preparation',lead:'A technically correct examination can still fail if the collection was unauthorized or poorly scoped.',points:[['Confirm authority','Record the legal, contractual or organizational basis for collection before touching the source.'],['Define scope','Identify permitted devices, accounts, dates, data types and actions. Avoid collecting beyond the authorized scope.'],['Prepare safely','Use clean media, trusted tools, synchronized clocks and a contemporaneous activity log.']],q:'What should happen before evidence collection?',opts:['Begin parsing immediately','Confirm authority and scope','Rename the source files'],answer:1},
 {title:'Identification & documentation',lead:'Evidence begins as a potential source whose state and context must be documented.',points:[['Identify the source','Record make, model, serial number, account, custodian, location and visible condition where applicable.'],['Capture context','Photograph connections and screens when authorized. Record power, network and encryption state.'],['Use unique identifiers','Assign an evidence ID that follows the item through collection, examination and reporting.']],q:'Which is an observed fact?',opts:['The suspect created the file','The device displayed 14:32 UTC','The account must belong to the custodian'],answer:1},
 {title:'Collection & acquisition',lead:'Collection secures the item; acquisition creates a controlled representation for examination.',points:[['Minimize change','Choose methods that avoid altering the source. Document unavoidable changes and their reason.'],['Validate copies','Calculate cryptographic hashes and compare them across transfers when the workflow supports it.'],['Retain originals','Perform examination on verified working copies whenever practical.']],q:'What is the preferred examination target?',opts:['The only original copy','A verified working copy','A screenshot of the filename'],answer:1},
 {title:'Preservation & chain of custody',lead:'Integrity is not only a hash. It is the documented history of possession, storage, transfer and access.',points:[['Record every transfer','Document who released and received the item, date/time, purpose and condition.'],['Protect access','Use tamper-evident controls, access restrictions and appropriate environmental protection.'],['Verify over time','Recalculate and compare hashes at defined workflow points; investigate any mismatch.']],q:'A hash alone proves:',opts:['Who created the evidence','That compared bytes match','That the evidence is legally admissible'],answer:1},
 {title:'Examination, interpretation & reporting',lead:'Tools produce observations. Examiners validate them, explain limitations and distinguish fact from inference.',points:[['Validate parser output','Compare important findings with original data, another method or a known-good test.'],['Preserve provenance','Link every reported event to its file, location, parser and raw time value.'],['Report limitations','State what was provided, what was done, what was not done and uncertainties affecting conclusions.']],q:'How should an entity suggestion be reported?',opts:['As a confirmed identity','As a lead requiring validation','It should be omitted automatically'],answer:1}
];
let lessonIndex=0,completed=new Set(JSON.parse(localStorage.getItem('tf-course')||'[]'));
function renderCourse(){
 const nav=document.querySelector('#courseNav');if(!nav)return;
 nav.innerHTML=lessons.map((l,i)=>`<button class="${i===lessonIndex?'active':''} ${completed.has(i)?'done':''}" data-lesson="${i}"><span>${String(i+1).padStart(2,'0')}</span>${l.title}</button>`).join('');
 nav.querySelectorAll('button').forEach(b=>b.onclick=()=>{lessonIndex=+b.dataset.lesson;renderCourse()});
 const l=lessons[lessonIndex],box=document.querySelector('#lesson');
 box.innerHTML=`<span class="lesson-tag">MODULE ${lessonIndex+1} OF ${lessons.length}</span><h2>${l.title}</h2><p class="lead">${l.lead}</p><div class="lesson-body">${l.points.map(p=>`<div class="lesson-point"><b>${p[0]}</b><p>${p[1]}</p></div>`).join('')}</div><div class="quiz"><h3>Knowledge check: ${l.q}</h3><div class="quiz-options">${l.opts.map((o,i)=>`<button data-answer="${i}">${o}</button>`).join('')}</div></div><div class="lesson-actions"><button class="quiet" id="prevLesson" ${lessonIndex===0?'disabled':''}>← Previous</button><button class="dark" id="nextLesson">${lessonIndex===lessons.length-1?'Finish course':'Next module →'}</button></div>`;
 box.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{box.querySelectorAll('[data-answer]').forEach(x=>x.disabled=true);const ok=+b.dataset.answer===l.answer;b.classList.add(ok?'correct':'wrong');if(!ok)box.querySelector(`[data-answer="${l.answer}"]`).classList.add('correct');else{completed.add(lessonIndex);localStorage.setItem('tf-course',JSON.stringify([...completed]));updateProgress();toast('Correct — module completed')}});
 document.querySelector('#prevLesson').onclick=()=>{if(lessonIndex){lessonIndex--;renderCourse()}};
 document.querySelector('#nextLesson').onclick=()=>{if(lessonIndex<lessons.length-1){lessonIndex++;renderCourse()}else toast(completed.size===lessons.length?'Course complete — well done':'Complete each knowledge check to finish')};
 updateProgress();
}
function updateProgress(){const pct=Math.round(completed.size/lessons.length*100);document.querySelector('#coursePercent').textContent=pct+'%';document.querySelectorAll('#courseNav button').forEach((b,i)=>b.classList.toggle('done',completed.has(i)))}
const tour=[
 ['Welcome to Traceframe','This guided demonstration shows the complete workflow. No evidence is uploaded; analysis happens on this device.','.brand'],
 ['Create or identify a case','The active case receives a unique identifier when evidence is first added. Use a separate case for each authorized investigation.','.case-name'],
 ['Add evidence safely','Drop any file here for SHA-256 hashing. Supported structured and text formats are also parsed into events.','#dropzone'],
 ['Review provenance','The Evidence register records filename, declared type, byte size, hash, extraction count and processing state.','nav [data-view="evidence"]'],
 ['Build the timeline','Extracted timestamps are normalized to UTC while raw source values remain represented in the case export.','nav [data-view="timeline"]'],
 ['Verify and export','Export the manifest and case bundle, record tool version and document every interpretation and limitation.','nav [data-view="integrity"]']
];let tourIndex=0;
function showTour(i=0){tourIndex=i;document.querySelectorAll('.tour-focus').forEach(x=>x.classList.remove('tour-focus'));const [title,text,sel]=tour[i],target=document.querySelector(sel);if(target)target.classList.add('tour-focus');document.querySelector('#tourCount').textContent=`STEP ${i+1} / ${tour.length}`;document.querySelector('#tourTitle').textContent=title;document.querySelector('#tourText').textContent=text;document.querySelector('#tourNext').textContent=i===tour.length-1?'Finish':'Next →';const layer=document.querySelector('#tourLayer');layer.classList.add('open');layer.setAttribute('aria-hidden','false')}
function closeTour(){document.querySelector('#tourLayer').classList.remove('open');document.querySelectorAll('.tour-focus').forEach(x=>x.classList.remove('tour-focus'))}
document.querySelector('#tourBtn').onclick=()=>showTour(0);document.querySelector('#guideTour').onclick=()=>showTour(0);document.querySelector('#tourClose').onclick=closeTour;document.querySelector('#tourNext').onclick=()=>tourIndex<tour.length-1?showTour(tourIndex+1):closeTour();renderCourse();
