const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={caseId:'TF-NEW',created:new Date().toISOString(),files:[],events:[],entities:new Map(),chain:[{action:'case_created',at:new Date().toISOString(),actor:'local_operator'}]};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const toast=m=>{const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)};
const human=n=>n<1024?n+' B':n<1048576?(n/1024).toFixed(1)+' KB':(n/1048576).toFixed(1)+' MB';
const sha=async b=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',b))].map(x=>x.toString(16).padStart(2,'0')).join('');
const signature=b=>{const h=[...new Uint8Array(b.slice(0,12))].map(x=>x.toString(16).padStart(2,'0')).join('');if(h.startsWith('25504446'))return'PDF';if(h.startsWith('89504e47'))return'PNG';if(h.startsWith('ffd8ff'))return'JPEG';if(h.startsWith('504b0304'))return'ZIP/OOXML';if(h.startsWith('1f8b'))return'GZIP';if(h.startsWith('4d5a'))return'Windows executable';if(h.startsWith('53514c697465'))return'SQLite';return'Unrecognized / text'};
const normalizeDate=v=>{if(v===null||v===undefined)return null;if(typeof v==='number'||/^\d{10,17}$/.test(String(v))){let n=Number(v);if(n>1e14)n/=1000;if(n>1e11)n/=1000;if(n>946684800&&n<4102444800){const d=new Date(n*1000);if(!isNaN(d))return d.toISOString()}}const d=new Date(v);return !isNaN(d)&&d.getUTCFullYear()>1990&&d.getUTCFullYear()<2101?d.toISOString():null};
const keyMatch=(o,names)=>Object.keys(o||{}).find(k=>names.some(n=>k.toLowerCase()===n||k.toLowerCase().includes(n)));
function addEntity(value,type,file){if(!value||String(value).length>180)return;const v=String(value).trim();if(!v)return;const key=type+'|'+v.toLowerCase();const old=state.entities.get(key)||{value:v,type,count:0,sources:new Set()};old.count++;old.sources.add(file);state.entities.set(key,old)}
function inspectText(text,file){
 const out=[];let m;const emails=text.match(/[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}/g)||[];emails.forEach(x=>addEntity(x,'email',file));
 const phones=text.match(/(?:\+?\d[\d ()-]{7,}\d)/g)||[];phones.slice(0,100).forEach(x=>addEntity(x.replace(/\s+/g,' '),'phone',file));
 const coords=text.match(/[-+]?([1-8]?\d(?:\.\d+)?|90(?:\.0+)?)[, ]+[-+]?(?:1[0-7]\d(?:\.\d+)?|180(?:\.0+)?|\d?\d(?:\.\d+)?)/g)||[];coords.slice(0,50).forEach(x=>addEntity(x,'location',file));
 const lines=text.split(/\r?\n/).slice(0,10000);
 for(let i=0;i<lines.length;i++){const line=lines[i];const tm=line.match(/(?:19|20)\d{2}[-\/.](?:0?[1-9]|1[0-2])[-\/.](?:0?[1-9]|[12]\d|3[01])(?:[T ,]+\d{1,2}:\d{2}(?::\d{2})?(?:\.\d+)?(?:Z|[+-]\d\d:?\d\d)?)?/);if(tm){const time=normalizeDate(tm[0]);if(time)out.push({time,raw_time:tm[0],type:'text_observation',title:'Timestamped text',detail:line.slice(0,500),source:file,row:i+1})}}
 return out;
}
function walkJSON(value,file,path='$',out=[]){
 if(out.length>5000)return out;
 if(Array.isArray(value)){value.forEach((v,i)=>walkJSON(v,file,`${path}[${i}]`,out));return out}
 if(!value||typeof value!=='object')return out;
 const tk=keyMatch(value,['timestamp','time','date','created_at','datetime','sent_at','start_time']);
 if(tk){const time=normalizeDate(value[tk]);if(time){const actorK=keyMatch(value,['sender','from','actor','user','username','email','name']);const msgK=keyMatch(value,['message','text','body','content','description','title','event']);const typeK=keyMatch(value,['type','event_type','action']);const actor=actorK?String(value[actorK]):'';const detail=msgK?String(value[msgK]):JSON.stringify(value).slice(0,500);out.push({time,raw_time:value[tk],type:typeK?String(value[typeK]):'record',title:actor?'Activity by '+actor:'Structured record',actor,detail,source:file,path});if(actor)addEntity(actor,actor.includes('@')?'email':'account',file)}}
 for(const [k,v] of Object.entries(value)){if(typeof v==='string'){if(/email|sender|recipient|from|to/i.test(k)&&v.includes('@'))addEntity(v,'email',file);if(/location|place|address|coordinates/i.test(k))addEntity(v,'location',file)}if(v&&typeof v==='object')walkJSON(v,file,path+'.'+k,out)}
 return out;
}
function parseCSV(text,file){const rows=text.split(/\r?\n/).filter(Boolean);if(rows.length<2)return[];const split=l=>{const a=[];let x='',q=false;for(let i=0;i<l.length;i++){const c=l[i];if(c==='"'&&l[i+1]==='"'&&q){x+='"';i++}else if(c==='"')q=!q;else if(c===','&&!q){a.push(x);x=''}else x+=c}a.push(x);return a};const headers=split(rows[0]);const arr=rows.slice(1,5001).map(r=>Object.fromEntries(split(r).map((v,i)=>[headers[i]||'column_'+i,v])));return walkJSON(arr,file)}
async function ingest(file){const buf=await file.arrayBuffer(),hash=await sha(buf),sig=signature(buf),duplicate=state.files.some(f=>f.hash===hash),ext=file.name.split('.').pop().toLowerCase(),parseable=['json','csv','txt','log','eml','xml','gpx','html','htm'].includes(ext),text=parseable&&file.size<=20*1024*1024?new TextDecoder('utf-8',{fatal:false}).decode(buf):'';let events=[];try{if(ext==='json')events=walkJSON(JSON.parse(text),file.name);else if(ext==='csv')events=parseCSV(text,file.name);else if(parseable)events=inspectText(text,file.name)}catch(e){events=inspectText(text,file.name)}events.forEach(e=>e.id=crypto.randomUUID());const at=new Date().toISOString();state.files.push({name:file.name,size:file.size,type:file.type||ext.toUpperCase()||'UNKNOWN',signature:sig,hash,duplicate,events:events.length,ingested:at,extraction:parseable?(file.size<=20*1024*1024?'parsed':'hash_only_size_limit'):'hash_only_unsupported'});state.chain.push({action:'evidence_ingested',at,evidence:file.name,sha256:hash,duplicate});state.events.push(...events)}
async function ingestMany(files){if(!files.length)return;$('#analysisState').textContent='Hashing and extracting…';for(const f of files)await ingest(f);state.events.sort((a,b)=>a.time.localeCompare(b.time));if(state.caseId==='TF-NEW'){state.caseId='TF-'+new Date().toISOString().slice(0,10).replaceAll('-','')+'-'+Math.random().toString(16).slice(2,6).toUpperCase();$('#caseId').textContent=state.caseId;$('#caseName').textContent='Evidence triage '+new Date().toLocaleDateString()}renderAll();$('#analysisState').textContent='Analysis complete';toast(`${files.length} evidence item${files.length>1?'s':''} processed locally`)}
function renderAll(){
 const fs=state.files,ev=state.events,ents=[...state.entities.values()];$('#fileCount').textContent=fs.length;$('#eventCount').textContent=ev.length;$('#entityCount').textContent=ents.length;$('#fileSize').textContent=human(fs.reduce((a,f)=>a+f.size,0))+' preserved';$('#integrityScore').textContent=fs.length?'100%':'—';$('#ringValue').textContent=fs.length;$('#integrityRing').style.setProperty('--pct',fs.length?'100%':'0%');$('#navFiles').textContent=fs.length;$('#navEvents').textContent=ev.length;$('#navEntities').textContent=ents.length;
 renderFiles();renderTimeline();renderEntities();renderManifest();renderMini();
}
function renderFiles(){const q=$('#fileSearch').value.toLowerCase();const list=state.files.filter(f=>Object.values(f).join(' ').toLowerCase().includes(q));$('#evidenceRows').innerHTML=list.map(f=>`<tr><td>${esc(f.name)}<small style="display:block;color:var(--muted);margin-top:4px">${esc(f.signature)}</small></td><td>${esc(f.type)}</td><td>${human(f.size)}</td><td class="hash" title="${f.hash}">${f.hash}</td><td>${f.events}</td><td><span class="pill">${f.duplicate?'DUPLICATE':'VERIFIED'}</span></td></tr>`).join('');$('#evidenceEmpty').style.display=list.length?'none':'flex';$('#evidenceTotal').textContent=`${list.length} items`}
function renderTimeline(){const q=$('#eventSearch').value.toLowerCase(),type=$('#eventType').value;const types=[...new Set(state.events.map(e=>e.type))].sort();const selected=$('#eventType').value;$('#eventType').innerHTML='<option value="">All event types</option>'+types.map(t=>`<option ${t===selected?'selected':''} value="${esc(t)}">${esc(t)}</option>`).join('');const list=state.events.filter(e=>(!type||e.type===type)&&Object.values(e).join(' ').toLowerCase().includes(q));$('#timelineTotal').textContent=`${list.length} events`;$('#timelineRows').innerHTML=list.length?list.map(e=>`<div class="time-row"><time>${esc(e.time)}</time><div><h4>${esc(e.title)}</h4><p>${esc(e.detail)}</p></div><div class="source"><b>${esc(e.type)}</b>${esc(e.source)}${e.row?' · line '+e.row:''}</div></div>`).join(''):'<div class="table-empty">No matching timeline events.</div>'}
function renderEntities(){const ents=[...state.entities.values()].sort((a,b)=>b.count-a.count);$('#entityGrid').innerHTML=ents.length?ents.map(e=>`<article class="entity-card"><header><span class="avatar">${esc(e.type.slice(0,2).toUpperCase())}</span><div><h3>${esc(e.value)}</h3><p>${esc(e.type.toUpperCase())}</p></div></header><footer><span>${e.count} observations</span><span>${e.sources.size} sources</span></footer></article>`).join(''):'<div class="table-empty">No entities extracted.</div>'}
function renderMini(){const x=state.events.slice(-4).reverse();$('#miniTimeline').className=x.length?'timeline-list':'';$('#miniTimeline').innerHTML=x.length?x.map(e=>`<div class="time-row"><time>${esc(e.time.slice(0,16).replace('T',' '))}Z</time><div><h4>${esc(e.title)}</h4><p>${esc(e.detail.slice(0,120))}</p></div><div class="source">${esc(e.source)}</div></div>`).join(''):'<b>No events yet</b><span>Add evidence or load the demonstration case.</span>'}
function manifest(){return{format:'traceframe-case',version:'0.2.0',case_id:state.caseId,created_at:state.created,exported_at:new Date().toISOString(),method:{hash:'SHA-256',processing:'device-local',network_enrichment:false,alignment:['ISO/IEC 27037 lifecycle terminology','NIST SP 800-86 practical forensic guidance','SWGDE collection best-practice awareness'],certification:false},evidence:state.files.map(({name,size,type,signature,hash,duplicate,extraction,ingested})=>({name,size,type,detected_signature:signature,sha256:hash,duplicate,extraction,ingested_at:ingested})),chain_of_custody:state.chain,event_count:state.events.length,entity_suggestions:state.entities.size,limitations:['Triage only; not forensic acquisition','No deleted data recovery','Entity matches require examiner validation','Legal admissibility depends on jurisdiction and complete process']}}
function renderManifest(){const m=manifest();$('#manifestTitle').textContent=state.files.length?`${state.files.length} evidence items verified`:'No evidence registered';$('#manifestPreview').textContent=state.files.length?JSON.stringify(m,null,2):'Add evidence to create a verifiable manifest.'}
function download(name,data,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),200)}
function exportCase(){download(`${state.caseId}-traceframe.json`,JSON.stringify({...manifest(),events:state.events,entities:[...state.entities.values()].map(e=>({...e,sources:[...e.sources]}))},null,2));toast('Reproducible case bundle exported')}
function demo(){const records=[{timestamp:'2026-08-14T08:42:11+01:00',type:'email',sender:'amina.rahman@example.org',recipient:'finance@example.org',message:'Please review invoice 8842 before the afternoon call.'},{timestamp:'2026-08-14T09:03:44+01:00',type:'login',actor:'a.rahman',location:'51.5074, -0.1278',description:'Successful browser sign-in'},{timestamp:'2026-08-14T09:18:02+01:00',type:'message',sender:'+44 7700 900123',message:'The transfer details changed. Use the new account.'},{timestamp:'2026-08-14T10:06:28Z',type:'file_access',actor:'a.rahman',description:'Opened Vendor_Payment_8842.pdf'}];const f=new File([JSON.stringify(records,null,2)],'demo-communications.json',{type:'application/json'});ingestMany([f])}
$$('nav button[data-view]').forEach(b=>b.onclick=()=>{$$('nav button').forEach(x=>x.classList.toggle('active',x===b));$$('.view').forEach(v=>v.classList.toggle('active',v.id===b.dataset.view))});$$('[data-jump]').forEach(b=>b.onclick=()=>document.querySelector(`nav [data-view="${b.dataset.jump}"]`).click());
const dz=$('#dropzone'),fi=$('#fileInput');fi.onchange=()=>{ingestMany([...fi.files]);fi.value=''};['dragenter','dragover'].forEach(x=>dz.addEventListener(x,e=>{e.preventDefault();dz.classList.add('drag')}));['dragleave','drop'].forEach(x=>dz.addEventListener(x,e=>{e.preventDefault();dz.classList.remove('drag')}));dz.addEventListener('drop',e=>ingestMany([...e.dataTransfer.files]));
$('#fileSearch').oninput=renderFiles;$('#eventSearch').oninput=renderTimeline;$('#eventType').onchange=renderTimeline;$('#sampleBtn').onclick=demo;$('#exportTop').onclick=exportCase;$('#downloadManifest').onclick=()=>download(`${state.caseId}-manifest.json`,JSON.stringify(manifest(),null,2));$('#timelineExport').onclick=()=>{const rows=[['time_utc','type','title','detail','source'],...state.events.map(e=>[e.time,e.type,e.title,e.detail,e.source])];download(`${state.caseId}-timeline.csv`,rows.map(r=>r.map(x=>'"'+String(x??'').replaceAll('"','""')+'"').join(',')).join('\n'),'text/csv')};$('#newCase').onclick=()=>location.reload();
renderAll();
