state.meta={title:'',reference:'',examiner:'',organization:'',jurisdiction:'',authority:'',scope:'',notes:''};state.findings=[];state.custody=[];
const metaFields=['Title','Reference','Examiner','Organization','Jurisdiction','Authority','Scope','Notes'];
const capabilities=[
 ['Universal SHA-256 registration','Hash and inventory any local file without uploading it.','functional'],['Structured event extraction','Nested JSON and CSV records with source paths and raw timestamps.','functional'],['Text artifact extraction','Timestamped lines, email addresses, phone numbers and coordinates.','functional'],['File signature recognition','Recognize selected common headers and compare them with declared types.','functional'],['Duplicate detection','Identify byte-identical evidence through matching SHA-256 digests.','functional'],['Unified UTC timeline','Normalize plausible times while retaining the original value.','functional'],['Entity suggestions','Group possible accounts, emails, phones and locations as investigative leads.','functional'],['Encrypted browser vault','AES-GCM local case storage protected by an operator passphrase.','functional'],['Case governance record','Authority, jurisdiction, scope, examiner and handling notes.','functional'],['Queries and examiner findings','Search derived case content and separate interpretation from observation.','functional'],['Portable reporting','JSON bundle, manifest, CSV timeline and printable browser report.','functional'],['EML / log interpretation','Heuristic text extraction; important results require manual validation.','experimental'],['GPX / XML interpretation','Timestamp and coordinate discovery without full schema validation.','experimental'],['File-signature classification','Small signature set; not a complete file identification engine.','experimental'],['Timestamp inference','Multiple common formats; ambiguous values remain a known risk.','experimental'],['E01, Ex01, AFF4 and RAW readers','Forensic image access through independently validated modules.','roadmap'],['Browser and SQLite artifacts','History, downloads, cookies and application databases.','roadmap'],['Windows forensic artifacts','EVTX, Registry, LNK, Jump Lists, Prefetch and Amcache.','roadmap'],['Mobile extraction imports','Vendor-neutral import of lawfully acquired mobile reports.','roadmap'],['Media laboratory','EXIF, perceptual hashes, thumbnails, OCR, QR and C2PA verification.','roadmap'],['Relationship graph','Evidence-linked people, accounts, devices, files and locations.','roadmap'],['Disclosure and redaction','Auditable redaction packages preserving internal originals.','roadmap'],['Plugin SDK and test corpus','Versioned parser contract, known-answer fixtures and regression suite.','roadmap'],['Desktop laboratory edition','Large-case processing with isolated, encrypted evidence storage.','roadmap']
];
function renderCapabilities(){document.querySelector('#capabilityTable').innerHTML=capabilities.map(c=>`<div class="cap-row"><b>${c[0]}</b><p>${c[1]}</p><span class="cap-state ${c[2]}">${c[2].toUpperCase()}</span></div>`).join('')}
function readMeta(){metaFields.forEach(k=>state.meta[k.toLowerCase()]=document.querySelector('#meta'+k).value.trim());state.chain.push({action:'case_metadata_updated',at:new Date().toISOString(),examiner:state.meta.examiner||'local_operator'});document.querySelector('#caseName').textContent=state.meta.title||'Untitled investigation';toast('Case governance record saved');renderManifest();persistDraft()}
function fillMeta(){metaFields.forEach(k=>{document.querySelector('#meta'+k).value=state.meta[k.toLowerCase()]||''})}
function renderCustody(){const box=document.querySelector('#custodyRows');box.innerHTML=state.custody.length?state.custody.map(x=>`<div class="custody-row"><time>${esc(x.at)}</time><div><b>${esc(x.action)}</b><br><span>${esc(x.details)}</span></div><span>${esc(x.actor||'local_operator')}</span></div>`).join(''):'<div class="table-empty">No manual handling entries. Automated ingestion events remain in the manifest.</div>'}
let entryMode='';
function openEntry(mode){entryMode=mode;const finding=mode==='finding';document.querySelector('#entryEyebrow').textContent=finding?'EXAMINER INTERPRETATION':'CHAIN OF CUSTODY';document.querySelector('#entryTitle').textContent=finding?'Add examiner finding':'Add handling entry';document.querySelector('#entryLabel').childNodes[0].nodeValue=finding?'Finding details':'Handling details';document.querySelector('#entryExtraLabel').childNodes[0].nodeValue=finding?'Classification':'Action';document.querySelector('#entryExtra').innerHTML=finding?'<option>Observation</option><option>Inference</option><option>Limitation</option><option>Action required</option>':'<option>Received</option><option>Transferred</option><option>Examined</option><option>Stored</option><option>Released</option><option>Verified</option>';document.querySelector('#entryText').value='';document.querySelector('#entryDialog').showModal()}
function commitEntry(){const text=document.querySelector('#entryText').value.trim(),type=document.querySelector('#entryExtra').value;if(!text)return toast('Enter details first');const rec={at:new Date().toISOString(),type,details:text,actor:state.meta.examiner||'local_operator'};if(entryMode==='finding'){state.findings.push(rec);renderFindings()}else{rec.action=type;state.custody.push(rec);state.chain.push({action:'custody_'+type.toLowerCase(),...rec});renderCustody()}document.querySelector('#entryDialog').close();persistDraft();toast('Record added')}
function renderFindings(){const box=document.querySelector('#findingList');box.innerHTML=state.findings.length?state.findings.map(x=>`<div class="finding-item"><b>${esc(x.type)}</b><p>${esc(x.details)}</p><small>${esc(x.at)} · ${esc(x.actor)}</small></div>`).join(''):'<div class="table-empty">No examiner findings recorded.</div>'}
function runQuery(){const q=document.querySelector('#globalQuery').value.trim().toLowerCase(),out=[];if(!q)return toast('Enter a search query');state.files.forEach(f=>{if(JSON.stringify(f).toLowerCase().includes(q))out.push(['Evidence',f.name,f.hash])});state.events.forEach(e=>{if(JSON.stringify(e).toLowerCase().includes(q))out.push(['Event',e.title,e.detail])});state.entities.forEach(e=>{if(JSON.stringify({value:e.value,type:e.type}).toLowerCase().includes(q))out.push(['Entity',e.value,e.type])});state.findings.forEach(e=>{if(JSON.stringify(e).toLowerCase().includes(q))out.push(['Finding',e.type,e.details])});document.querySelector('#queryResults').innerHTML=out.length?out.slice(0,200).map(x=>`<div class="query-result"><b>${esc(x[0])}: ${esc(x[1])}</b><p>${esc(x[2])}</p></div>`).join(''):'<div class="table-empty">No derived case content matched this query.</div>'}
function casePayload(){return{...manifest(),case_metadata:state.meta,custody_entries:state.custody,examiner_findings:state.findings,events:state.events,entities:[...state.entities.values()].map(e=>({...e,sources:[...e.sources]}))}}
function printReport(){const p=casePayload(),w=open('','_blank');if(!w)return toast('Allow pop-ups to create the report');w.document.write(`<!doctype html><title>Traceframe report</title><style>body{font:14px system-ui;max-width:900px;margin:50px auto;color:#17201e}h1{font-size:34px}h2{border-bottom:1px solid #ccc;padding-bottom:8px;margin-top:35px}table{width:100%;border-collapse:collapse}td,th{border:1px solid #ddd;padding:8px;text-align:left}code{font-size:10px;word-break:break-all}.note{background:#f1f2eb;padding:15px}</style><h1>Traceframe Forensic Triage Report</h1><p class="note">Triage report generated locally. This report is not a certification of authenticity or legal admissibility.</p><h2>Case</h2><table>${Object.entries(p.case_metadata).map(x=>`<tr><th>${esc(x[0])}</th><td>${esc(x[1])}</td></tr>`).join('')}</table><h2>Evidence</h2><table><tr><th>Item</th><th>Size</th><th>SHA-256</th></tr>${p.evidence.map(e=>`<tr><td>${esc(e.name)}</td><td>${e.size}</td><td><code>${e.sha256}</code></td></tr>`).join('')}</table><h2>Examiner findings</h2>${p.examiner_findings.map(f=>`<p><b>${esc(f.type)}</b> — ${esc(f.details)}</p>`).join('')||'<p>None recorded.</p>'}<h2>Limitations</h2><ul>${p.limitations.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><script>print()<\/script>`);w.document.close()}
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open('traceframe-vault',1);r.onupgradeneeded=()=>r.result.createObjectStore('cases',{keyPath:'id'});r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function derive(pass,salt){const base=await crypto.subtle.importKey('raw',new TextEncoder().encode(pass),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:250000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
const b64=a=>btoa(String.fromCharCode(...new Uint8Array(a))),unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
async function saveVault(){const pass=document.querySelector('#vaultPass').value;if(pass.length<8)return toast('Use at least 8 characters');const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await derive(pass,salt),plain=new TextEncoder().encode(JSON.stringify(casePayload())),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,plain),db=await openDB(),tx=db.transaction('cases','readwrite');tx.objectStore('cases').put({id:state.caseId,salt:b64(salt),iv:b64(iv),cipher:b64(cipher),updated:new Date().toISOString()});document.querySelector('#vaultStatus').textContent='Encrypted case saved locally: '+state.caseId;toast('Case encrypted and saved in this browser')}
async function vaultRecords(){const db=await openDB();return new Promise((res,rej)=>{const r=db.transaction('cases').objectStore('cases').getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function listVault(){const rows=await vaultRecords();document.querySelector('#vaultStatus').innerHTML=rows.length?rows.map(x=>`<div>${esc(x.id)} · ${esc(x.updated)}</div>`).join(''):'No encrypted cases saved in this browser.'}
async function restoreVault(){const pass=document.querySelector('#vaultPass').value,rows=await vaultRecords();if(!rows.length)return toast('No saved cases found');if(pass.length<8)return toast('Enter the case passphrase');const x=rows.sort((a,b)=>b.updated.localeCompare(a.updated))[0];try{const key=await derive(pass,unb64(x.salt)),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(x.iv)},key,unb64(x.cipher)),p=JSON.parse(new TextDecoder().decode(plain));state.caseId=p.case_id;state.created=p.created_at;state.meta=p.case_metadata||state.meta;state.custody=p.custody_entries||[];state.findings=p.examiner_findings||[];state.files=(p.evidence||[]).map(e=>({name:e.name,size:e.size,type:e.type,signature:e.detected_signature,hash:e.sha256,duplicate:e.duplicate,extraction:e.extraction,events:0,ingested:e.ingested_at}));state.events=p.events||[];state.chain=p.chain_of_custody||[];state.entities=new Map((p.entities||[]).map(e=>[e.type+'|'+e.value.toLowerCase(),{...e,sources:new Set(e.sources||[])}]));document.querySelector('#caseId').textContent=state.caseId;fillMeta();renderCustody();renderFindings();renderAll();document.querySelector('#vaultDialog').close();toast('Encrypted case restored')}catch{return toast('Could not decrypt: check the passphrase')}}
function persistDraft(){localStorage.setItem('tf-case-meta',JSON.stringify({meta:state.meta,custody:state.custody,findings:state.findings}))}
function loadDraft(){try{const d=JSON.parse(localStorage.getItem('tf-case-meta'));if(d){state.meta=d.meta||state.meta;state.custody=d.custody||[];state.findings=d.findings||[]}}catch{}fillMeta();renderCustody();renderFindings()}
function support(channel){const name=document.querySelector('#supportName').value.trim(),subject=document.querySelector('#supportSubject').value.trim(),message=document.querySelector('#supportMessage').value.trim();if(!subject||!message)return toast('Enter a subject and message');const body=`Traceframe query from ${name||'a user'}\n\n${message}`;if(channel==='mail')location.href=`mailto:Braveomar7@gmail.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;else open(`https://wa.me/220833853607?text=${encodeURIComponent(subject+'\n'+body)}`,'_blank')}
const printBtn=document.createElement('button');printBtn.className='quiet';printBtn.textContent='Print report';printBtn.onclick=printReport;document.querySelector('.top-actions').insertBefore(printBtn,document.querySelector('#exportTop'));
document.querySelector('#vaultBtn').onclick=()=>document.querySelector('#vaultDialog').showModal();document.querySelector('#saveVault').onclick=saveVault;document.querySelector('#listVault').onclick=listVault;document.querySelector('#restoreVault').onclick=restoreVault;document.querySelector('#saveCaseMeta').onclick=readMeta;document.querySelector('#addCustody').onclick=()=>openEntry('custody');document.querySelector('#addFinding').onclick=()=>openEntry('finding');document.querySelector('#commitEntry').onclick=commitEntry;document.querySelector('#runQuery').onclick=runQuery;document.querySelector('#globalQuery').onkeydown=e=>{if(e.key==='Enter')runQuery()};document.querySelector('#supportForm').onsubmit=e=>{e.preventDefault();support('mail')};document.querySelector('#queryWhatsApp').onclick=()=>support('whatsapp');renderCapabilities();loadDraft();
