const traceframeIngest=ingest;
let processCancelled=false,processStarted=0,processTimer=null,tipTimer=null;
const processTips=['Original evidence is never modified by Traceframe.','A matching hash demonstrates matching bytes—not who created them.','Validate important parser results against the original source.','Unknown time zones should remain unknown, not silently assumed.','Document authority and scope before collecting evidence.','Examiner conclusions belong in Findings, separate from observations.'];
const waitFrame=()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));
function processTime(ms){const s=Math.floor(ms/1000);return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
function processLog(text){const log=document.querySelector('#processLog'),row=document.createElement('div');row.textContent=text;log.appendChild(row);log.scrollTop=log.scrollHeight}
function setProcessStage(stage,label){document.querySelector('#processStage').textContent=label;const order=['read','hash','extract','index','verify'],at=order.indexOf(stage);document.querySelectorAll('.stage-rail span').forEach((x,i)=>{x.classList.toggle('active',i===at);x.classList.toggle('done',i<at)})}
function openProcess(total){const box=document.querySelector('#processConsole');box.classList.add('open');box.classList.remove('finished','minimized');box.setAttribute('aria-hidden','false');document.querySelector('#processLog').innerHTML='';document.querySelector('#processCounter').textContent='0 of '+total+' files';document.querySelector('#processBar').style.width='0%';document.querySelector('#processPercent').textContent='0%';document.querySelector('#processEta').textContent='Estimating…';document.querySelector('#processDone').classList.add('hidden');processStarted=Date.now();processCancelled=false;processTimer=setInterval(()=>document.querySelector('#processElapsed').textContent=processTime(Date.now()-processStarted)+' elapsed',1000);let i=0;document.querySelector('#processTip').textContent=processTips[0];tipTimer=setInterval(()=>{i=(i+1)%processTips.length;document.querySelector('#processTip').textContent=processTips[i]},4500)}
function finishProcess(done,total,bytes,cancelled=false){clearInterval(processTimer);clearInterval(tipTimer);setProcessStage('verify','Verifying case integrity');document.querySelectorAll('.stage-rail span').forEach(x=>{x.classList.remove('active');x.classList.add('done')});document.querySelector('#processBar').style.width=(cancelled?Math.round(done/total*100):100)+'%';document.querySelector('#processPercent').textContent=(cancelled?Math.round(done/total*100):100)+'%';document.querySelector('#processEta').textContent='Complete';document.querySelector('#processSummary').textContent=cancelled?`Stopped after ${done} files`:`${done} files · ${human(bytes)} processed`;document.querySelector('#processStage').textContent=cancelled?'Processing cancelled':'Evidence processing complete';document.querySelector('#processConsole').classList.add('finished');document.querySelector('#processDone').classList.remove('hidden');processLog(cancelled?'Remaining files were not processed.':'Case indexes and integrity manifest updated.')}
ingestMany=async function(files){files=[...files];if(!files.length)return;openProcess(files.length);document.querySelector('#analysisState').textContent='Processing evidence…';const totalBytes=files.reduce((n,f)=>n+f.size,0),started=Date.now();let completedBytes=0,done=0;for(const file of files){if(processCancelled)break;document.querySelector('#processCounter').textContent=`File ${done+1} of ${files.length}`;document.querySelector('#processFile').textContent=file.name;document.querySelector('#processSize').textContent=human(file.size);setProcessStage('read','Reading evidence safely');processLog(`Opened ${file.name} (${human(file.size)})`);await waitFrame();setProcessStage('hash','Calculating SHA-256 fingerprint');processLog('Hashing original bytes; large files may take longer.');await waitFrame();const beforeEvents=state.events.length;await traceframeIngest(file);setProcessStage('extract','Extracting supported artifacts');await waitFrame();const added=state.events.length-beforeEvents;processLog(added?`Extracted ${added} timestamped events.`:'Hash registered; no supported events extracted.');setProcessStage('index','Indexing provenance and entities');await waitFrame();completedBytes+=file.size;done++;const pct=totalBytes?Math.round(completedBytes/totalBytes*100):Math.round(done/files.length*100),elapsed=Date.now()-started,eta=completedBytes?elapsed*(totalBytes-completedBytes)/completedBytes:0;document.querySelector('#processBar').style.width=pct+'%';document.querySelector('#processPercent').textContent=pct+'%';document.querySelector('#processEta').textContent=eta>0?'~'+processTime(eta)+' remaining':'Finishing…';processLog('Evidence record committed to the local case.')}
 state.events.sort((a,b)=>a.time.localeCompare(b.time));if(state.caseId==='TF-NEW'&&done){state.caseId='TF-'+new Date().toISOString().slice(0,10).replaceAll('-','')+'-'+Math.random().toString(16).slice(2,6).toUpperCase();document.querySelector('#caseId').textContent=state.caseId;document.querySelector('#caseName').textContent='Evidence triage '+new Date().toLocaleDateString()}renderAll();document.querySelector('#analysisState').textContent=processCancelled?'Processing stopped':'Analysis complete';finishProcess(done,files.length,completedBytes,processCancelled);toast(processCancelled?'Processing stopped safely':`${done} evidence item${done===1?'':'s'} processed locally`)}
document.querySelector('#processCancel').onclick=()=>{processCancelled=true;document.querySelector('#processCancel').disabled=true;document.querySelector('#processCancel').textContent='Stopping after current file…';processLog('Cancellation requested; completing the current operation safely.')};document.querySelector('#processDone').onclick=()=>document.querySelector('#processConsole').classList.remove('open');document.querySelector('#processMinimize').onclick=()=>{const box=document.querySelector('#processConsole');box.classList.toggle('minimized');document.querySelector('#processMinimize').textContent=box.classList.contains('minimized')?'□':'—'};
const traceframeProgressManifest=manifest;manifest=()=>({...traceframeProgressManifest(),version:'0.4.0',processing_ui:{file_progress:true,stage_visibility:true,cancellation:'after_current_file'}});
